"""Renders backtest/results.json as backtest/RESULTS.md so documented numbers always come from the data.

Run:  python -m backtest.report
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def pct(x, signed=True):
    return "n/a" if x is None else f"{x * 100:+.1f}%" if signed else f"{x * 100:.1f}%"


def table(models: dict, period: str) -> str:
    rows = [
        "| Model | BUY / HOLD / SELL share | BUY hit rate | SELL hit rate | Avg 30-day return after BUY / HOLD / SELL | Rank IC | BUY-only CAGR | Equal-weight CAGR |",
        "| :--- | :--- | ---: | ---: | :--- | ---: | ---: | ---: |",
    ]
    for name, periods in models.items():
        m = periods[period]
        share, avg = m["share"], m["avg_fwd_return"]
        rows.append(
            f"| {name} | {share['BUY']:.1%} / {share['HOLD']:.1%} / {share['SELL']:.1%} "
            f"| {pct(m['buy_hit_rate'], False)} | {pct(m['sell_hit_rate'], False)} "
            f"| {pct(avg['BUY'])} / {pct(avg['HOLD'])} / {pct(avg['SELL'])} "
            f"| {m['rank_ic']:+.3f} | {pct(m['strategy_cagr'])} | {pct(m['equal_weight_cagr'])} |"
        )
    return "\n".join(rows)


def main() -> None:
    results = json.loads((HERE / "results.json").read_text(encoding="utf-8"))
    cfg, models = results["config"], results["models"]
    base = next(iter(models.values()))["out_of_sample_2019_on"]["base_rate_up"]
    tilt_rows = "\n".join(f"| {t} | {ic:+.4f} |" for t, ic in cfg["tilt_in_sample_ic"].items())
    md = f"""# Backtest results

Generated by `python -m backtest.run_backtest` then `python -m backtest.report`. Do not edit by hand.

**Setup.** {len(cfg['universe'])} large-cap US stocks, {cfg['start']} to {cfg['end']}, daily adjusted closes from Yahoo Finance.
Every {cfg['horizon_trading_days']} trading days each stock gets a call using only trailing data (1-year beta vs SPY,
1-year realized volatility, distance from the 52-week high), simulated with the app's Monte Carlo engine
({cfg['paths']:,} paths). BUY means the fractional-Kelly size is above zero; SELL means the 30-day probability of profit is
below {cfg['sell_below_p_profit']:.0%}; otherwise HOLD. Calls do not overlap. Parameters were chosen on data before
{cfg['split']} and the held-out period was scored once.

**Out-of-sample base rate:** {base:.1%} of 30-day windows ended higher.

## Held out: {cfg['split']} onward

{table(models, 'out_of_sample_2019_on')}

## In sample: before {cfg['split']}

{table(models, 'in_sample_2011_2018')}

## 52-week-high tilt selection (in sample, rank IC)

| Tilt | In-sample rank IC |
| ---: | ---: |
{tilt_rows}

Chosen tilt: **{cfg['chosen_tilt']}**. Negative values bet on short-term reversal (stocks near their high do worse next month).

## Reading the numbers

* **Rank IC** is the rank correlation between the forecast median return and the realized return. Zero means no
  ranking skill; the sign matters more than the size at these levels.
* **BUY hit rate** should be compared with the base rate. Matching it means the BUY call carries no information
  beyond "stocks usually go up".
* **Small buckets:** when a call's share is under about 1%, its average return rests on a handful of trades and
  says nothing.
* **Caveats:** current index members only (survivorship bias), no trading costs, constant risk-free rate, and a
  small universe. The LLM committee is not part of the backtest: it cannot be replayed without look-ahead, because
  the model has seen what happened next.
"""
    (HERE / "RESULTS.md").write_text(md, encoding="utf-8")
    print(md)


if __name__ == "__main__":
    main()
